server:
  port: 8090

spring:
  application:
    name: CLIENT
  datasource:
    url: jdbc:mysql://localhost:3306/utilisateur-ms
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update