spring:
  application:
    name: Blog_ms2
  datasource:
    password: ""
    username: "root"
    url: jdbc:mysql://localhost:3306/commentsmsdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
